import Landing from '@/components/Landing';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hyperion",
  description: "Generated by create next app",
};

export default function LandingPage() {
  return <Landing />
}
