import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hyperion",
  description: "Generated by create next app",
};

export default function MainPage() {
  return <div>You are on the main page</div>
}
